version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - weedly-backend

  weedly-backend:
    image: kbondar17/weedly-backend
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - weedly-backend

  weedly-parser:
    image: kbondar17/weedly-parser
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - weedly-backend

networks:
  weedly-backend: null
