version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - weedly-backend

  weedly-backend:
    image: ghcr.io/weedly-23/backend:v1.0.4
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - weedly-backend

  weedly-parser:
    image: ghcr.io/weedly-23/rss-parsers:main
    restart: always
    env_file:
      - .env
    networks:
      - weedly-backend

  weedly-bot:
    image: ghcr.io/weedly-23/weedly-tg-bot:v1.0.1
    restart: always
    env_file:
      - .env
    networks:
      - weedly-backend

networks:
  weedly-backend: null
