version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - weedly-backend

  weedly-backend:
    image: ghcr.io/weedly-23/backend:main
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - weedly-backend

  weedly-parser:
    image: kbondar17/rss-parser
    restart: always
    env_file:
      - .env
    networks:
      - weedly-backend

networks:
  weedly-backend: null
